version: "3.9"
services:

  mysql:
    image: mysql:8.0
    container_name: clinic_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicdb
      MYSQL_USER: clinicuser
      MYSQL_PASSWORD: clinicpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: clinic_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  clinicservice:
    build:
      context: ../backend/ClinicService
      dockerfile: Dockerfile
    container_name: clinic_service
    ports:
      - "5000:8080"
    depends_on:
      - mysql
      - minio

volumes:
  mysql_data:
  minio_data:
